#! /bin/sh

# Startup programs
sxhkd &
compton &
polybar bar &
nm-applet &
redshift &

timedatectl set-ntp 1

# Keyboard settings
setxkbmap -layout us,lt
setxkbmap -option 'grp:alt_shift_toggle'
setxkbmap -option caps:escape

# Bspwm settings
bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Firefox desktop='^2'
bspc rule -a Steam desktop='^10'
